version: '3'
services:
  odoo:
    image: odoo:15.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
